# Generated by Django 5.2 on 2026-03-12 04:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('movement', 'Price Movement Analysis'), ('volatility', 'Volatility Analysis'), ('correlation', 'Correlation Analysis'), ('scenario', 'What-If Scenario')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField()),
                ('results', models.JSONField()),
                ('chart', models.ImageField(blank=True, null=True, upload_to='reports/charts/')),
                ('csv_export', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_days', models.IntegerField()),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('correlation_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'period_days')},
            },
        ),
        migrations.CreateModel(
            name='WhatIfScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rules', models.JSONField(default=dict, help_text='\n        {\n            "entry": {\n                "type": "price_drop",\n                "threshold": -10,\n                "lookback_days": 1\n            },\n            "exit": {\n                "type": "price_target",\n                "target": 5,\n                "max_hold_days": 20\n            },\n            "filters": {\n                "min_volume": 1000000,\n                "max_volatility": 50\n            }\n        }\n    ')),
                ('results', models.JSONField(blank=True, default=dict)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceMovementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movement_type', models.CharField(choices=[('rise', 'Rise'), ('fall', 'Fall')], max_length=20)),
                ('threshold_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_movement_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('end_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume_during_move', models.BigIntegerField()),
                ('avg_volume_prev_20d', models.BigIntegerField()),
                ('subsequent_1d_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subsequent_5d_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subsequent_20d_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.symbol')),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['movement_type', 'threshold_pct'], name='analysis_pr_movemen_f60058_idx'), models.Index(fields=['date'], name='analysis_pr_date_06e53b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolatilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hv_10d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('hv_30d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('hv_60d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('hv_percentile_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hv_percentile_90d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('atr_14', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('atr_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('beta_spy_30d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('beta_spy_90d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('regime', models.CharField(choices=[('low', 'Low Volatility'), ('normal', 'Normal Volatility'), ('high', 'High Volatility'), ('extreme', 'Extreme Volatility')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.symbol')),
            ],
            options={
                'ordering': ['symbol', '-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
