# Generated by Django 5.2 on 2026-03-12 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('above', 'Above Threshold'), ('below', 'Below Threshold'), ('cross_above', 'Cross Above'), ('cross_below', 'Cross Below'), ('volatility', 'Volatility Spike')], max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lookback_days', models.IntegerField(default=1)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='IntradayPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(choices=[('1min', '1 Minute'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours')], max_length=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_prices', to='stocks.symbol')),
            ],
            options={
                'ordering': ['symbol', 'granularity', 'datetime'],
                'indexes': [models.Index(fields=['symbol', 'granularity', 'datetime'], name='stocks_intr_symbol__94fcc0_idx')],
                'unique_together': {('symbol', 'datetime', 'granularity')},
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('daily_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('daily_range', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.symbol')),
            ],
            options={
                'ordering': ['symbol', 'date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='stocks_dail_symbol__71aca2_idx'), models.Index(fields=['date'], name='stocks_dail_date_a52485_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sma_20', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('sma_50', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('sma_200', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('ema_20', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('bollinger_upper', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('bollinger_lower', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('atr_14', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('rsi_14', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('macd', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('macd_signal', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('macd_histogram', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('volume_sma_20', models.BigIntegerField(null=True)),
                ('obv', models.BigIntegerField(null=True)),
                ('volatility_30d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('volatility_90d', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('beta', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='stocks.symbol')),
            ],
            options={
                'ordering': ['symbol', 'date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
